{% set name = "dicom2nifti" %}
{% set version = "2.2.12" %}
{% set sha256 = "9b05418cff4737b631cb5d77b26296e68ffd11c7c4a4aadaf5fb894a8c69c95d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/icometrix/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - setuptools
  run:
    - python
    - pydicom
    - numpy
    - nibabel
    - scipy

test:
  imports:
    - dicom2nifti
  requires:
    - setuptools
  
about:
  home: http://github.com/icometrix/dicom2nifti
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python library for converting dicom files to nifti'
  description: 'Python library for converting dicom files to nifti'
  doc_url: https://icometrix.github.io/dicom2nifti/
  dev_url: http://github.com/icometrix/dicom2nifti

extra:
  recipe-maintainers:
    - abrys
